baseURL = "https://teaca.eu"
languageCode = "en-gb"
title = "T blog"
theme = "ananke"
publishdir = "docs"
staticDir = ["static"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/img/t_32.png"
  site_logo = "/img/t_32.png"
  description = "T blog"
  facebook = ""
  twitter = "https://twitter.com/teacai"
  instagram = ""
  youtube = ""
  github = "https://github.com/teacai"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  post_content_classes = "helvetica"
  body_classes = "helvetica"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
  show_reading_time = true